mode = "dark"
accent = "#D5AE6E"
selection = "#463A29"
selection_foreground = "#F2E5CF"
selection_background = "#463A29"
muted = "#AD9977"
background = "#080808"
dark_background = "#040404"
darker_background = "#000000"
lighter_background = "#181714"
foreground = "#E8D7B8"
dark_foreground = "#AD9977"
light_foreground = "#CBB38B"
bright_foreground = "#F2E5CF"
hyprland_active_border = "#D5AE6E"
hyprland_inactive_border = "#5A4932"
red = "#E8D7B8"
green = "#D5AE6E"
yellow = "#CBB38B"
orange = "#CBB38B"
blue = "#D5AE6E"
magenta = "#E8D7B8"
cyan = "#AD9977"
brown = "#AD9977"
bright_red = "#F2E5CF"
bright_green = "#E8D7B8"
bright_yellow = "#F2E5CF"
bright_blue = "#CBB38B"
bright_magenta = "#E8D7B8"
bright_cyan = "#D5AE6E"
