[bar]
background = "#080808"
background-alpha = 0.0
text = "#E8D7B8"
active = "#E8D7B8"
scale-with-font = true
size-horizontal = 26
size-vertical = 28

[hyprland]
active-border = "#D5AE6E"
active-border-foreground = "#D5AE6E"

[controls]
normal-color = "#E8D7B8"
normal-fill-alpha = 0.04
normal-border = "#E8D7B8"
normal-border-width = 1
normal-border-alpha = 0.4
hover-cursor-color = "#D5AE6E"
hover-cursor-fill-alpha = 0.08
hover-cursor-border = "#D5AE6E"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.25
focus-color = "#D5AE6E"
focus-fill-alpha = 0.08
focus-border = "#D5AE6E"
focus-border-width = 1
focus-border-alpha = 0.65
selected-color = "#D5AE6E"
selected-fill-alpha = 0.18
selected-border = "#D5AE6E"
selected-border-width = 0
selected-border-alpha = 1.0
pressed-fill-alpha = 0.22
selection-fill-alpha = 0.35

[spacing]
scale = 1.0
scale-with-font = true

[font]
base-size = 12

[popups]
background = "#080808"
background-alpha = 1.0
text = "#E8D7B8"
border = "#5A4932"
border-alpha = 1.0
border-width = 1

[tooltip]
background = "#080808"
background-alpha = 1.0
text = "#E8D7B8"
border = "#5A4932"
border-alpha = 1.0

[notifications]
background = "#080808"
background-alpha = 1.0
text = "#E8D7B8"
border = "#5A4932"
border-alpha = 1.0
border-width = 1
countdown = "#D5AE6E"

[launcher]
background = "#080808"
background-alpha = 1.0
text = "#E8D7B8"
border = "#5A4932"
border-alpha = 1.0
scrim = "#000000"
scrim-alpha = 0.35
selected-background = "#463A29"
selected-background-alpha = 1.0
selected-text = "#F2E5CF"
selected-border = "#D5AE6E"
selected-border-alpha = 0.35

[menu]
background = "#080808"
background-alpha = 1.0
text = "#E8D7B8"
border = "#5A4932"
border-alpha = 1.0
scrim = "#000000"
scrim-alpha = 0.35
selected-background = "#463A29"
selected-background-alpha = 1.0
selected-text = "#F2E5CF"
selected-border = "#D5AE6E"
selected-border-alpha = 0.35

[polkit]
background = "#080808"
background-alpha = 1.0
text = "#E8D7B8"
text-error = "#D5A397"
border = "hyprland.active-border"
border-error = "#D5A397"
border-alpha = 1.0
scrim = "#000000"
scrim-alpha = 0.5
accent = "#D5AE6E"

[lock]
background = "#080808"
background-alpha = 1.0
text = "#E8D7B8"
placeholder = "#AD9977"
text-error = "#D5A397"
border = "#5A4932"
border-active = "#D5AE6E"
border-error = "#D5A397"
border-alpha = 1.0
selection = "#D5AE6E"
selection-alpha = 0.15

[image-picker]
scrim = "#000000"
scrim-alpha = 0.5
text = "#E8D7B8"
selected-border = "#D5AE6E"
selected-border-alpha = 1.0
unselected-border = "#E8D7B8"
unselected-border-alpha = 0.28
